wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.12
    session_history: code/_session_history.ipynb
    start_time: 1634997256
    t:
      1:
      - 1
      2:
      - 1
      - 3
      3:
      - 2
      - 13
      4: 3.8.12
      5: 0.12.4
      8:
      - 1
      - 5
